#!/usr/bin/env python

# Copyright (C) 2012 Massimo Santini <massimo.santini@unimi.it>
#
# This file is part of Learning-Week-2012-Software.
# 
# Learning-Week-2012-Software is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
# 
# Learning-Week-2012-Software is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	See the GNU General
# Public License for more details.
# 
# You should have received a copy of the GNU General Public License along with
# Learning-Week-2012-Software If not, see <http://www.gnu.org/licenses/>.

from json import load
from os.path import expanduser
from subprocess import Popen, PIPE
from sys import argv

__version__ = '0.1.0'

_, user, repo, dlid = argv

def curl( args, data = None ):
	p = Popen( [ 'curl', '-s' ] + ( [ '-d', '@-' ] if data else [] ) + args, stdin = PIPE, stdout = PIPE )
	return p.communicate( dumps( data ) if data else None )[ 0 ]

with open( expanduser( '~/.gdu-tokens.json' ), 'r' ) as f:
	token = load( f )[ user ]

print curl( [
	'-H', 'Authorization: token {0}'.format( token ),
	'-X', 'DELETE', '-i',
	'https://api.github.com/repos/{0}/{1}/downloads/{2}'.format( user, repo, dlid )
] )
